version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  ms-teams-notifier: oktapodia/ms-teams-notifier@1.0.0
jobs:
  build:
    executor: docker
    steps:
      - ms-teams-notifier/report:
          webhook_url: https://studenthcmusedu.webhook.office.com/webhookb2/64f4cb9f-db48-403d-98b6-82a997fcc5e8@40127cd4-45f3-49a3-b05d-315a43a9f033/IncomingWebhook/8cc534bbb90c41cab7edfa56ab72545c/ab0f24bd-0fc0-4a20-9f51-52ff8e728636
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git